name: Security Analysis Snyk
description: Corre SCA, SAST, y Docker analisis con Snyk sube los resultados a GHAS.
inputs:
  docker-image-name:
    description: 'Nombre de la imagen Docker a scanear'
    required: true
    
runs:
  using: "composite"
  steps:
    #Auth: identificarse en snyk
    - name: Authenticate and Scan DVWA image with Snyk
      shell: powershell
      run: |
        snyk auth $env:SNYK_TOKEN
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
        
    # SCA: Análisis de dependencias
    - name: Dependency Analysis (SCA)
      shell: powershell
      run: snyk test --sarif > snyk-dependencies.sarif
     
    # SAST: Análisis estático de código
    - name: Static Code Analysis (SAST)
      shell: powershell  
      run: snyk code test . --sarif > snyk-code.sarif

    # Docker: Análisis de la imagen
    - name: Docker Image Analysis
      shell: powershell
      run: snyk container test ${{ inputs.docker-image-name }} --sarif > snyk-docker.sarif


    # Subir los reportes a GHAS
    - name: Upload Dependency Report to GitHub Advanced Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-dependencies.sarif

    - name: Upload SAST Report to GitHub Advanced Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-code.sarif

    - name: Upload Docker Report to GitHub Advanced Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-docker.sarif
