name: Security Analysis Snyk
description: Corre SCA, SAST, y Docker analisis con Snyk sube los resultados a GHAS.
inputs:
  docker-image-name:
    description: 'Nombre de la imagen Docker a scanear'
    required: true
    
runs:
  using: "composite"
  steps:
    # SCA: Análisis de dependencias
    - name: Dependency Analysis (SCA)
      run: snyk test --sarif > snyk-dependencies.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # SAST: Análisis estático de código
    - name: Static Code Analysis (SAST)
      run: snyk code test . --sarif > snyk-code.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # Docker: Análisis de la imagen
    - name: Docker Image Analysis
      run: snyk container test ${{ inputs.docker-image-name }} --sarif > snyk-docker.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # Subir los reportes a GHAS
    - name: Upload Dependency Report to GitHub Advanced Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-dependencies.sarif

    - name: Upload SAST Report to GitHub Advanced Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-code.sarif

    - name: Upload Docker Report to GitHub Advanced Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-docker.sarif
