name: Build and Run DVWA

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build DVWA Docker image
        run: |
          docker build -t dvwa-app .

      - name: Run DVWA in Docker
        run: |
          docker run -d -p 8080:80 --name dvwa-app dvwa-app

      - name: Verify DVWA is running
        run: |
          curl -I http://localhost:8080

