name: Build and Run DVWA

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build DVWA Docker image
        run: |
          docker compose up -d
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}



