name: Build and Run DVWA

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build DVWA Docker image
        run: |
          docker compose up -d
          
      - name: Authenticate and Scan DVWA image with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        shell: powershell
        run: |
          # Autenticación en Snyk
          snyk auth $env:SNYK_TOKEN
          
          # Ejecuta el análisis de Snyk
          snyk code test 

      - name: Stop and Clean Up DVWA
        if: always()
        run: |
          docker compose down



