name: Build and Run DVWA

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build DVWA Docker image
        run: |
          docker compose up -d
      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          docker run --rm -e SNYK_TOKEN=$SNYK_TOKEN snyk/snyk-cli:docker snyk auth $SNYK_TOKEN

      - name: Scan DVWA image with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          docker run --rm -e SNYK_TOKEN=$SNYK_TOKEN snyk/snyk-cli:docker snyk container test ghcr.io/digininja/dvwa:latest



